### PR TITLE
Add FAQ showing what HyBox will be compatible with

### PR DESCRIPTION
**Pull request by mjgiarlo**
Also rejiggers the order of the questions to group those related to config/customization/compatibility.

Fixes hybox/project-planning#62, hybox/project-planning#63, hybox/project-planning#74

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@hannahfrost @anarchivist Your thoughts?

**Comment by hannahfrost** [comment]
@mjgiarlo, regarding the phrasing, "there is a ... gem that may be used to build this customization": I can't tell if you mean "we may decide to add this to HyBox based on requirements" or if you mean "one (as in someone else, not necessarily us) will have the choice to customize HyBox for this funcitonality

**Comment by mjgiarlo** [comment]
@hannahfrost on it.

**Comment by mjgiarlo** [comment]
@hannahfrost Have a :eyes: - https://github.com/hybox/hybox.github.io/commit/16aff8e27b38b08f738509019de07f831cc8f7bc#diff-a5599031fb964daec56823d37b187931R39

**Comment by anarchivist** [comment]
With @hannahfrost's suggestions I'm :+1:

**Comment by mjgiarlo** [comment]
@hannahfrost @anarchivist Done. Have a last look?

**Comment by anarchivist** [comment]
:ok_hand:

**Comment by hannahfrost** [comment]
:+1:

**Pull request merged**
