### PR TITLE
Add a blog post on the value of PCDM and its usage in HyBox

### PR DESCRIPTION
**Pull request by mjgiarlo**
@anarchivist @hannahfrost Note that this is more or less identical to the Quickbyte video. If there are bits that y'all think could use unpacking or further prose, let me know and I'm happy to develop this post further.

Closes https://github.com/hybox/project-planning/issues/77

### CODE REVIEW

**Comment by anarchivist** [comment]
Can we change the width/height of the iframe to embed the video? Here's how it's rendering in my browser...

screen shot 2016-01-29 at 2 16 48 pm

**Comment by mjgiarlo** [comment]
@anarchivist Yep. On it.

**Comment by mjgiarlo** [comment]
@anarchivist Done. And I threw in image scaling for the PCDM graphic while I was at it.

**Comment by anarchivist** [comment]
@mjgiarlo :+1: ... but can you remove the `width` and `height` attributes on the `<iframe/>` tag?

**Comment by mjgiarlo** [comment]
@anarchivist I don't think so, no. Then browsers use their default iframe height, which causes only a sliver of the frame to be shown. I've tested the code above to make sure it'll work at lots o' different widths and it does based on my testing. Wrapping the iframe in a div looks like a common workaround.

**Comment by anarchivist** [comment]
Sounds good to me, thanks!

**Pull request merged**
