### PR TITLE
Add FAQs to project website

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes hybox/project-planning#81

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Fixes hybox/project-planning#81

**Comment by mjgiarlo** [comment]
The mixing of HTML into the YAML is a bit janky, but it works for now Same re: how I handled styles (of the embedded image and the definition list). If y'all feel strongly about my handling this differently, pls advise.

**Comment by mjgiarlo** [comment]
Needs review by @anarchivist and @hannahfrost.

**Comment by hannahfrost** [comment]
@mjgiarlo ++
Looks good to me. Is there anyway to preview the faq.html page?

**Comment by mjgiarlo** [comment]
Oh, whoops. I took screenshots and failed to upload them. On their way...

**Comment by mjgiarlo** [comment]
screenshot from 2015-12-14 15 56 18
screenshot from 2015-12-14 15 56 10

**Comment by hannahfrost** [comment]
@mjgiarlo That'll work as a preview! Looks super. Thanks for doing the heavy lifting on that.

**Comment by mjgiarlo** [comment]
np!

**Comment by anarchivist** [comment]
:+1:

**Pull request merged**
