### PR TITLE
Repo update blog post (to be published Thursday, September 15th)

### PR DESCRIPTION
**Pull request by mjgiarlo**
Also includes a new plugin to remove footnotes from the bottom of post excerpts.

### CODE REVIEW

**Comment by hannahfrost** [comment]
Would you be open to turning this into a co-authored post and adding my name? Hope that doesn't seem like an odd request, but the information presented here was definitely a team effort and I think there's broader value in presenting it that way.

**Comment by mjgiarlo** [comment]
@hannahfrost yes, of course!

**Comment by mjgiarlo** [comment]
@hannahfrost done.

**Comment by hannahfrost** [comment]
Thanks, @mjgiarlo, and no worries at all. I made minor text edits and now merging.

**Pull request merged**
